"""Casino Tycoon — build-your-own-casino idle/active hybrid.

Three-currency model:
  chips  ($T) — internal grind currency, generated by units when occupied
  cash   ($)  — mid-tier, converted from chips at the cashier (player UX)
  coins  (🪙) — main app currency, converted from cash at the bank (capped/day)
  vip    ⭐   — prestige tokens, gained only via full reset

Game tick: server runs a periodic 'tick' on every state-fetch call (idempotent,
based on last_tick_at delta). During the tick:
  • each unit accrues chips into its tray, scaled by occupancy and bot bonuses
  • cashier bot auto-converts a fraction of chips to cash
  • slot-attendant bot auto-collects trays into chips
  • staff salaries are deducted

Visitor spawning is purely visual on the frontend — server doesn't simulate
individual visitors. Instead it computes an aggregate occupancy_pct per unit
based on the current reputation + unit tier + bot bonuses, and the frontend
samples that to drive the visual show.
"""
from __future__ import annotations

import json
import logging
import math
import random
from datetime import datetime, timezone
from pathlib import Path

from app.db.client import pool

log = logging.getLogger(__name__)


# ============================================================
# CONFIG / CATALOG (will be seeded into tycoon_units_catalog)
# ============================================================

# (key, name, kind, tier, cost_cash, cost_chips, base_chips_per_sec, capacity, unlock_rep, icon, desc)
UNIT_CATALOG: list[dict] = [
    # ----- SLOTS (stack vertically across tiers) -----
    {"key": "slot_basic",    "name": "Slot Basic",    "kind": "slot", "tier": 1,
     "cost_cash": 500,    "cost_chips": 0,     "base_chips_per_sec": 5,    "capacity": 1, "unlock_rep": 0,
     "icon": "🎰", "description": "Старушка-однорукий, копейки но капают всегда"},
    {"key": "slot_lucky7",   "name": "Lucky 7",       "kind": "slot", "tier": 2,
     "cost_cash": 2_500,  "cost_chips": 0,     "base_chips_per_sec": 18,   "capacity": 1, "unlock_rep": 1.0,
     "icon": "7️⃣", "description": "Красные семёрки, любимая бабушек на пенсии"},
    {"key": "slot_pirate",   "name": "Pirate Booty",  "kind": "slot", "tier": 3,
     "cost_cash": 8_000,  "cost_chips": 0,     "base_chips_per_sec": 50,   "capacity": 1, "unlock_rep": 1.5,
     "icon": "🏴‍☠️", "description": "Сундук, попугай, x100 на трёх якорях"},
    {"key": "slot_royale",   "name": "Royal Flush",   "kind": "slot", "tier": 4,
     "cost_cash": 25_000, "cost_chips": 0,     "base_chips_per_sec": 150,  "capacity": 1, "unlock_rep": 2.5,
     "icon": "👑", "description": "Премиум для среднего класса"},
    {"key": "slot_csgates",  "name": "CS Gates",      "kind": "slot", "tier": 5,
     "cost_cash": 80_000, "cost_chips": 0,     "base_chips_per_sec": 400,  "capacity": 1, "unlock_rep": 3.5,
     "icon": "💣", "description": "Тематический под наш main-game CS Gates"},

    # ----- TABLES (multi-seat) -----
    {"key": "tbl_coinflip",  "name": "Стол Coinflip", "kind": "table", "tier": 2,
     "cost_cash": 5_000,  "cost_chips": 0,     "base_chips_per_sec": 25,   "capacity": 2, "unlock_rep": 1.0,
     "icon": "🪙", "description": "Простейшая дуэль 1v1"},
    {"key": "tbl_roulette",  "name": "Рулетка",       "kind": "table", "tier": 3,
     "cost_cash": 30_000, "cost_chips": 0,     "base_chips_per_sec": 200,  "capacity": 6, "unlock_rep": 2.0,
     "icon": "🎡", "description": "Классика, 6 мест, красное-чёрное-зелёное"},
    {"key": "tbl_blackjack", "name": "Блэкджек",      "kind": "table", "tier": 4,
     "cost_cash": 50_000, "cost_chips": 0,     "base_chips_per_sec": 320,  "capacity": 4, "unlock_rep": 2.5,
     "icon": "🃏", "description": "21, дилер раздаёт без устали"},
    {"key": "tbl_poker_vip", "name": "Покер VIP",     "kind": "table", "tier": 5,
     "cost_cash": 200_000,"cost_chips": 0,     "base_chips_per_sec": 1500, "capacity": 6, "unlock_rep": 3.5,
     "icon": "♠", "description": "Высокие ставки, заходят только хайроллеры"},

    # ----- AMENITIES (don't generate chips directly, boost others) -----
    {"key": "amen_bar",      "name": "Бар",           "kind": "amenity", "tier": 2,
     "cost_cash": 15_000, "cost_chips": 0,     "base_chips_per_sec": 0,    "capacity": 4, "unlock_rep": 1.5,
     "icon": "🍸", "description": "+20% к среднему кошельку гостя (через repu)"},
    {"key": "amen_atm",      "name": "Банкомат",      "kind": "amenity", "tier": 2,
     "cost_cash": 25_000, "cost_chips": 0,     "base_chips_per_sec": 0,    "capacity": 1, "unlock_rep": 2.0,
     "icon": "🏧", "description": "Гости тратят больше; +reputation"},
    {"key": "amen_vip",      "name": "VIP-зона",      "kind": "amenity", "tier": 5,
     "cost_cash": 1_000_000, "cost_chips": 0,  "base_chips_per_sec": 0,    "capacity": 1, "unlock_rep": 4.0,
     "icon": "🌟", "description": "Открывает приток китов; огромный реп-бонус"},
]


# ============================================================
# BOT TYPES (effects applied at tick)
# ============================================================

BOT_KINDS: dict[str, dict] = {
    "slot_attendant": {
        "name":          "Слот-аттендант",
        "icon":          "🧑‍🔧",
        "hire_cost":     5_000,    # cash
        "salary_per_hr": 300,      # chips/hour
        "max_count":     5,
        "description":   "Авто-собирает подносы со слотов (1 бот = 5 слотов)",
    },
    "cashier": {
        "name":          "Кассир",
        "icon":          "💼",
        "hire_cost":     10_000,
        "salary_per_hr": 200,
        "max_count":     1,
        "description":   "Авто-конверсия 50% накопленных чипов в $ при тике",
    },
    "dealer": {
        "name":          "Дилер",
        "icon":          "🃏",
        "hire_cost":     30_000,
        "salary_per_hr": 500,
        "max_count":     5,
        "description":   "+50% к скорости столов",
    },
    "manager": {
        "name":          "Менеджер",
        "icon":          "🎩",
        "hire_cost":     200_000,
        "salary_per_hr": 2_000,
        "max_count":     1,
        "description":   "+15% к доходу всего казино",
    },
    "cleaner": {
        "name":          "Уборщик",
        "icon":          "🧹",
        "hire_cost":     2_000,
        "salary_per_hr": 50,
        "max_count":     3,
        "description":   "+0.5⭐ к репутации (за бота, до +1.5)",
    },
    "guard": {
        "name":          "Охранник",
        "icon":          "🛡",
        "hire_cost":     8_000,
        "salary_per_hr": 400,
        "max_count":     3,
        "description":   "−10% шанс рейдеру за бота (до −30%, защита кассы)",
    },
}


# ============================================================
# ECONOMY CONSTANTS
# ============================================================

CHIPS_TO_CASH_RATE   = 100              # 100 chips → 1 $ (player click conversion)
CASH_TO_COINS_RATE   = 1_000            # 1000 $ → 1 coin (bank conversion)
COINS_DAILY_CAP_BASE = 5_000            # base daily coin-conversion cap
PRESTIGE_THRESHOLD   = 1_000_000_000    # $1B lifetime cash to unlock prestige

START_FLOOR_CAPACITY = 6                # 3x2 grid at start
MAX_FLOOR_CAPACITY   = 24               # 6x4 endgame
CELL_BUY_BASE_COST   = 5_000            # cost to unlock cell N+1
CELL_BUY_GROWTH      = 1.6              # multiplied per cell

DECOR_REP_PER_RARITY = {                # reputation bonus per displayed skin
    "consumer": 0.0, "industrial": 0.0, "mil-spec": 0.05,
    "restricted": 0.1, "classified": 0.2,
    "covert": 0.4, "exceedingly_rare": 0.8,
}


# ============================================================
# THEMES — visual variants + economic bonuses
# ============================================================

THEMES: dict[str, dict] = {
    "vegas": {
        "key":         "vegas",
        "name":        "Vegas Classic",
        "icon":        "🎰",
        "cost":        0,
        "income_mult": 1.00,
        "rep_delta":   0.0,
        "description": "Стандартная американская классика. Приветствует всех гостей.",
    },
    "macau": {
        "key":         "macau",
        "name":        "Macau Dragon",
        "icon":        "🐉",
        "cost":        1_000_000,
        "income_mult": 1.10,
        "rep_delta":   0.2,
        "description": "Восточная роскошь. +10% дохода, +0.2⭐ к репутации.",
    },
    "underground": {
        "key":         "underground",
        "name":        "Underground",
        "icon":        "🕴",
        "cost":        5_000_000,
        "income_mult": 1.20,
        "rep_delta":   -1.0,
        "description": "Гаражное казино, нет правил. +20% дохода, −1⭐ к репутации.",
    },
    "cs": {
        "key":         "cs",
        "name":        "CS Theme",
        "icon":        "🔫",
        "cost":        10_000_000,
        "income_mult": 1.15,
        "rep_delta":   0.3,
        "description": "Гости — CT и T бойцы. Тематика CS2. +15% дохода.",
    },
    "cosmic": {
        "key":         "cosmic",
        "name":        "Cosmic",
        "icon":        "🌌",
        "cost":        50_000_000,
        "income_mult": 1.30,
        "rep_delta":   0.5,
        "description": "Премиум-эффекты, частицы, +30% дохода.",
    },
}


# ============================================================
# STREAK / CELEB / RAID config
# ============================================================

STREAK_HOT_CHANCE   = 0.04   # per tick (~5s polling)
STREAK_COLD_CHANCE  = 0.04
STREAK_DURATION_SEC = 60
STREAK_HOT_BONUS    = 1.25
STREAK_COLD_PENALTY = 0.75

CELEB_CHANCE        = 0.02   # per tick when reputation ≥ 3.5
CELEB_DURATION_SEC  = 600    # 10 min
CELEB_INCOME_MULT   = 1.50
CELEB_NAMES         = [
    "s1mple", "ZywOo", "Oleksandr", "Dread", "Игорь-Лудоман",
    "Лагурман", "Пашабиаз", "Jame", "boombl4", "Эминем",
]

RAID_COOLDOWN_HOURS = 6
RAID_STEAL_PCT      = 0.05   # 5% of victim's unbanked cash
RAID_SUCCESS_BASE   = 0.30   # 30% base success
RAID_BONUS_PER_GUARD = -0.10 # each guard bot = -10% to attacker success

NEWS_MAX_ITEMS = 10


# ============================================================
# DAILY MISSIONS templates
# ============================================================

TYCOON_DAILY_TEMPLATES = [
    {"key": "earn_chips_50k",  "name": "Заработать 50k чипов",     "metric": "chips_earned",   "target": 50_000,    "reward_chips": 5_000},
    {"key": "earn_chips_500k", "name": "Заработать 500k чипов",    "metric": "chips_earned",   "target": 500_000,   "reward_chips": 25_000},
    {"key": "collect_30",      "name": "Собрать с подносов 30 раз","metric": "trays_collected","target": 30,        "reward_chips": 8_000},
    {"key": "buy_2_units",     "name": "Купить 2 юнита",           "metric": "units_bought",   "target": 2,         "reward_chips": 12_000},
    {"key": "hire_bot",        "name": "Нанять бота",              "metric": "bots_hired",     "target": 1,         "reward_chips": 6_000},
    {"key": "convert_cash",    "name": "Сконвертить в $",          "metric": "cash_converted", "target": 1_000,     "reward_chips": 4_000},
    {"key": "convert_coins",   "name": "Сконвертить в 🪙",          "metric": "coins_converted","target": 100,       "reward_chips": 15_000},
]


# ============================================================
# SCHEMA + SEED
# ============================================================

async def ensure_schema() -> None:
    """Apply schema in granular steps so a single failing statement can't
    leave the DB half-initialised. Each CREATE/ALTER runs in its own
    transaction; failures are logged but don't abort the rest.
    """
    statements: list[tuple[str, str]] = [
        ("tycoon_state", """
            create table if not exists tycoon_state (
                user_id              bigint primary key references users(tg_id) on delete cascade,
                chips                bigint  not null default 0,
                cash                 bigint  not null default 1000,
                vip_stars            int     not null default 0,
                floor_capacity       int     not null default 6,
                reputation_stars     real    not null default 1.0,
                theme                text    not null default 'vegas',
                last_tick_at         timestamptz not null default now(),
                last_bank_conv_day   date,
                bank_conv_today      bigint  not null default 0,
                total_lifetime_cash  bigint  not null default 0,
                prestige_count       int     not null default 0,
                created_at           timestamptz not null default now(),
                updated_at           timestamptz not null default now()
            )
        """),
        ("tycoon_units_catalog", """
            create table if not exists tycoon_units_catalog (
                key                  text primary key,
                name                 text  not null,
                kind                 text  not null,
                tier                 int   not null default 1,
                cost_cash            bigint not null default 0,
                cost_chips           bigint not null default 0,
                base_chips_per_sec   real  not null default 0,
                capacity             int   not null default 1,
                unlock_reputation    real  not null default 0,
                icon                 text,
                description          text
            )
        """),
        ("tycoon_units", """
            create table if not exists tycoon_units (
                id              bigserial primary key,
                user_id         bigint not null references users(tg_id) on delete cascade,
                unit_key        text   not null references tycoon_units_catalog(key) on delete cascade,
                cell_x          int    not null,
                cell_y          int    not null,
                level           int    not null default 1,
                chips_in_tray   bigint not null default 0,
                occupancy_pct   real   not null default 0,
                last_collected_at timestamptz not null default now(),
                placed_at       timestamptz not null default now()
            )
        """),
        ("idx_tycoon_units_user", "create index if not exists idx_tycoon_units_user on tycoon_units (user_id)"),
        ("tycoon_bots", """
            create table if not exists tycoon_bots (
                id              bigserial primary key,
                user_id         bigint not null references users(tg_id) on delete cascade,
                kind            text   not null,
                level           int    not null default 1,
                hired_at        timestamptz not null default now()
            )
        """),
        ("idx_tycoon_bots_user", "create index if not exists idx_tycoon_bots_user on tycoon_bots (user_id)"),
        ("tycoon_decor", """
            create table if not exists tycoon_decor (
                id              bigserial primary key,
                user_id         bigint not null references users(tg_id) on delete cascade,
                inv_id          bigint not null,
                slot_index      int    not null,
                placed_at       timestamptz not null default now()
            )
        """),
        ("idx_tycoon_decor_user", "create index if not exists idx_tycoon_decor_user on tycoon_decor (user_id)"),

        # Phase 2 columns
        ("themes_owned",       "alter table tycoon_state add column if not exists themes_owned jsonb not null default '[\"vegas\"]'::jsonb"),
        ("streak_kind",        "alter table tycoon_state add column if not exists streak_kind text not null default 'neutral'"),
        ("streak_until",       "alter table tycoon_state add column if not exists streak_until timestamptz"),
        ("celeb_until",        "alter table tycoon_state add column if not exists celeb_until timestamptz"),
        ("celeb_name",         "alter table tycoon_state add column if not exists celeb_name text"),
        ("last_raid_at",       "alter table tycoon_state add column if not exists last_raid_at timestamptz"),
        ("last_raided_at",     "alter table tycoon_state add column if not exists last_raided_at timestamptz"),
        ("news",               "alter table tycoon_state add column if not exists news jsonb not null default '[]'::jsonb"),

        ("tycoon_daily_missions", """
            create table if not exists tycoon_daily_missions (
                user_id     bigint not null references users(tg_id) on delete cascade,
                day         date   not null,
                missions    jsonb  not null,
                primary key (user_id, day)
            )
        """),
        ("idx_tycoon_dm_user", "create index if not exists idx_tycoon_dm_user on tycoon_daily_missions (user_id, day)"),
    ]

    async with pool().acquire() as conn:
        for label, stmt in statements:
            try:
                await conn.execute(stmt)
            except Exception as e:
                log.warning("tycoon schema: %s failed: %s", label, e)
        # Seed catalog rows (idempotent: ON CONFLICT updates)
        for u in UNIT_CATALOG:
            try:
                await conn.execute(
                    """
                    insert into tycoon_units_catalog
                      (key, name, kind, tier, cost_cash, cost_chips, base_chips_per_sec,
                       capacity, unlock_reputation, icon, description)
                    values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
                    on conflict (key) do update set
                      name = excluded.name, kind = excluded.kind, tier = excluded.tier,
                      cost_cash = excluded.cost_cash, cost_chips = excluded.cost_chips,
                      base_chips_per_sec = excluded.base_chips_per_sec,
                      capacity = excluded.capacity,
                      unlock_reputation = excluded.unlock_reputation,
                      icon = excluded.icon, description = excluded.description
                    """,
                    u["key"], u["name"], u["kind"], u["tier"],
                    u["cost_cash"], u["cost_chips"], u["base_chips_per_sec"],
                    u["capacity"], u["unlock_rep"], u["icon"], u["description"],
                )
            except Exception as e:
                log.warning("tycoon catalog seed %s failed: %s", u.get("key"), e)
    log.info("tycoon schema + catalog (%d units) ensured", len(UNIT_CATALOG))


# ============================================================
# CORE — get state (also runs the offline tick)
# ============================================================

async def _ensure_state(conn, user_id: int) -> None:
    """Create initial state row + 1 starter slot if user is brand new."""
    row = await conn.fetchrow("select user_id from tycoon_state where user_id = $1", user_id)
    if row is not None:
        return
    await conn.execute(
        "insert into tycoon_state (user_id, chips, cash, floor_capacity, reputation_stars) "
        "values ($1, 0, 1000, $2, 1.0)",
        user_id, START_FLOOR_CAPACITY,
    )
    # Starter slot at cell (1,0) — center of top row
    await conn.execute(
        "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, 1, 0)",
        user_id, "slot_basic",
    )


def _bot_counts(rows: list) -> dict[str, int]:
    out: dict[str, int] = {}
    for r in rows:
        out[r["kind"]] = out.get(r["kind"], 0) + 1
    return out


def _compute_occupancy(reputation: float, unit_tier: int, manager_bonus: float) -> float:
    """0..1 occupancy estimate. Higher rep = more visitors. Higher-tier units
    need more rep to fill up — they only really shine at 4-5 stars."""
    rep_factor    = max(0.0, min(1.0, (reputation - 0.5) / 4.5))
    tier_demand   = 1.0 - 0.10 * (unit_tier - 1)   # tier 5 needs ~1.4× more rep
    base = 0.20 + 0.65 * rep_factor * tier_demand
    return max(0.0, min(0.95, base * manager_bonus))


def _chips_per_sec_for_unit(u: dict, occupancy: float, dealer_factor: float, manager_bonus: float) -> float:
    """Effective chips/sec considering occupancy + dealer (tables) + manager."""
    base = float(u["base_chips_per_sec"]) * (1.0 + 0.5 * (u["level"] - 1))
    dealer_mult = dealer_factor if u["kind"] == "table" else 1.0
    return base * occupancy * dealer_mult * manager_bonus


async def get_state(user_id: int) -> dict:
    """Read state, run offline tick, return full snapshot for the frontend.

    On first-deploy race conditions where the schema migration is still
    running (Render free tier can be slow), self-heals by calling
    ensure_schema() once and retrying.
    """
    try:
        return await _get_state_inner(user_id)
    except Exception as e:
        msg = str(e)
        if 'tycoon_' in msg.lower() and ('does not exist' in msg.lower() or 'undefinedtableerror' in msg.lower()):
            log.warning("tycoon schema not ready, re-running ensure_schema and retrying")
            try:
                await ensure_schema()
            except Exception:
                pass
            return await _get_state_inner(user_id)
        raise


async def _theme_bonuses(state: dict) -> tuple[float, float]:
    """Return (income_mult, rep_delta) for the currently selected theme."""
    theme = (state.get("theme") or "vegas")
    cfg = THEMES.get(theme, THEMES["vegas"])
    return float(cfg["income_mult"]), float(cfg["rep_delta"])


def _resolve_streak(state: dict, now: datetime) -> tuple[str, datetime | None, float]:
    """Return (kind, until, income_mult). Resolves expiry + chance to enter a new streak."""
    kind  = state.get("streak_kind") or "neutral"
    until = state.get("streak_until")
    if kind != "neutral" and until and until < now:
        kind, until = "neutral", None
    if kind == "neutral":
        roll = random.random()
        if roll < STREAK_HOT_CHANCE:
            kind, until = "hot",  now + timedelta(seconds=STREAK_DURATION_SEC)
        elif roll < STREAK_HOT_CHANCE + STREAK_COLD_CHANCE:
            kind, until = "cold", now + timedelta(seconds=STREAK_DURATION_SEC)
    mult = STREAK_HOT_BONUS if kind == "hot" else (STREAK_COLD_PENALTY if kind == "cold" else 1.0)
    return kind, until, mult


def _resolve_celeb(state: dict, reputation: float, now: datetime) -> tuple[datetime | None, str | None, float]:
    """Roll for celebrity visit. Active celeb gives +50% income for 10 min."""
    until = state.get("celeb_until")
    name  = state.get("celeb_name")
    if until and until < now:
        until, name = None, None
    if until is None and reputation >= 3.5 and random.random() < CELEB_CHANCE:
        until = now + timedelta(seconds=CELEB_DURATION_SEC)
        name  = random.choice(CELEB_NAMES)
    mult = CELEB_INCOME_MULT if (until and until > now) else 1.0
    return until, name, mult


async def _push_news(conn, user_id: int, msg: str) -> None:
    """Append a string to the user's news feed (capped at NEWS_MAX_ITEMS)."""
    cur = await conn.fetchval("select news from tycoon_state where user_id = $1", user_id)
    items = []
    if cur:
        items = cur if isinstance(cur, list) else json.loads(cur)
    ts = datetime.now(timezone.utc).isoformat()
    items.append({"t": ts, "msg": msg})
    items = items[-NEWS_MAX_ITEMS:]
    await conn.execute(
        "update tycoon_state set news = $2::jsonb where user_id = $1",
        user_id, json.dumps(items),
    )


async def _get_state_inner(user_id: int) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            await _ensure_state(conn, user_id)
            state = dict(await conn.fetchrow("select * from tycoon_state where user_id = $1", user_id))
            unit_rows = await conn.fetch(
                "select u.*, c.kind, c.tier, c.base_chips_per_sec, c.capacity, c.icon, c.name as unit_name "
                "from tycoon_units u join tycoon_units_catalog c on c.key = u.unit_key "
                "where u.user_id = $1 order by u.placed_at",
                user_id,
            )
            bot_rows = await conn.fetch(
                "select * from tycoon_bots where user_id = $1", user_id,
            )
            decor_rows = await conn.fetch(
                "select d.id, d.inv_id, d.slot_index, "
                "       i.id as inv_exists, i.skin_id, i.price, i.rarity, "
                "       s.full_name, s.image_url, s.rarity as cat_rarity "
                "from tycoon_decor d "
                "left join economy_inventory i on i.id = d.inv_id "
                "left join economy_skins_catalog s on s.id = i.skin_id "
                "where d.user_id = $1 order by d.slot_index",
                user_id,
            )

            now = datetime.now(timezone.utc)
            elapsed = (now - state["last_tick_at"]).total_seconds()
            elapsed = max(0.0, min(elapsed, 12 * 3600))   # cap offline at 12h

            # Bot effects
            bots = _bot_counts(bot_rows)
            n_attendants    = bots.get("slot_attendant", 0)
            has_cashier     = bots.get("cashier", 0) > 0
            n_dealers       = bots.get("dealer", 0)
            has_manager     = bots.get("manager", 0) > 0
            n_cleaners      = bots.get("cleaner", 0)
            dealer_factor   = 1.0 + 0.5 * min(n_dealers, 5)         # +50% per dealer up to 5
            manager_bonus   = 1.15 if has_manager else 1.0
            cleaner_rep     = min(1.5, 0.5 * n_cleaners)
            decor_rep_bonus = 0.0
            for d in decor_rows:
                rar = d.get("cat_rarity") or d.get("rarity")
                if rar and d.get("inv_exists") is not None:
                    decor_rep_bonus += DECOR_REP_PER_RARITY.get(rar, 0.0)
            decor_rep_bonus = min(2.0, decor_rep_bonus)              # cap so single user can't grind 5⭐ via decor only

            # Reputation = 1 (base) + 0.4 per amenity + cleaner_rep + decor + theme bonus
            n_amenities = sum(1 for u in unit_rows if u["kind"] == "amenity")
            theme_income_mult, theme_rep_delta = await _theme_bonuses(state)
            reputation = 1.0 + 0.4 * n_amenities + cleaner_rep + decor_rep_bonus + theme_rep_delta
            reputation = max(0.0, min(5.0, reputation))

            # Streak + celeb modifiers (rolled on each tick)
            streak_kind, streak_until, streak_mult = _resolve_streak(state, now)
            celeb_until, celeb_name, celeb_mult   = _resolve_celeb(state, reputation, now)
            global_income_mult = theme_income_mult * streak_mult * celeb_mult
            # If celeb just appeared (was None, now set) — push news
            if celeb_until and celeb_until > now and (state.get("celeb_until") is None or state.get("celeb_until") < now):
                try:
                    await _push_news(conn, user_id,
                        f"🌟 {celeb_name} зашёл в твоё казино! +50% дохода 10 минут")
                except Exception:
                    pass

            # Run tick: each unit accrues chips, attendants auto-collect, cashier auto-converts
            new_chips = int(state["chips"])
            new_cash  = int(state["cash"])
            occupancy_per_unit: dict[int, float] = {}
            chips_per_sec_per_unit: dict[int, float] = {}
            for u in unit_rows:
                occ = _compute_occupancy(reputation, int(u["tier"]), manager_bonus)
                cps = _chips_per_sec_for_unit(dict(u), occ, dealer_factor, manager_bonus) * global_income_mult
                occupancy_per_unit[u["id"]]    = occ
                chips_per_sec_per_unit[u["id"]] = cps
                gen = int(cps * elapsed)
                if gen <= 0:
                    continue
                # Attendants auto-collect a fraction of generated chips into the player's wallet.
                # Otherwise chips pile up in the unit's tray for manual collection.
                if u["kind"] in ("slot", "table") and n_attendants > 0:
                    auto_pct = min(1.0, n_attendants * 0.20)         # 1 bot=20%, 5 bots=100%
                    auto_part = int(gen * auto_pct)
                    tray_part = gen - auto_part
                    new_chips += auto_part
                    if tray_part > 0:
                        await conn.execute(
                            "update tycoon_units set chips_in_tray = chips_in_tray + $2, "
                            "occupancy_pct = $3, last_collected_at = greatest(last_collected_at, $4) "
                            "where id = $1",
                            int(u["id"]), tray_part, occ * 100, now,
                        )
                    else:
                        await conn.execute(
                            "update tycoon_units set occupancy_pct = $2 where id = $1",
                            int(u["id"]), occ * 100,
                        )
                else:
                    await conn.execute(
                        "update tycoon_units set chips_in_tray = chips_in_tray + $2, occupancy_pct = $3 "
                        "where id = $1",
                        int(u["id"]), gen, occ * 100,
                    )

            # Cashier auto-converts wallet chips to cash periodically
            if has_cashier and new_chips > 200:
                conv_chips = int(new_chips * 0.50)                   # 50% per tick
                conv_cash  = conv_chips // CHIPS_TO_CASH_RATE
                if conv_cash > 0:
                    new_chips -= conv_chips
                    new_cash  += conv_cash

            # Salaries (per-hour rate × elapsed hours), paid in chips
            salary_chips = 0
            for kind, count in bots.items():
                cfg = BOT_KINDS.get(kind)
                if cfg:
                    salary_chips += int(cfg["salary_per_hr"] * count * (elapsed / 3600.0))
            if salary_chips > 0:
                if new_chips >= salary_chips:
                    new_chips -= salary_chips
                else:
                    # Player went negative — bots quietly stop working (no -chips, but log)
                    salary_chips = new_chips
                    new_chips = 0

            # Persist state changes from tick (incl. streak / celeb)
            await conn.execute(
                "update tycoon_state set chips = $2, cash = $3, reputation_stars = $4, last_tick_at = $5, "
                "streak_kind = $6, streak_until = $7, celeb_until = $8, celeb_name = $9, "
                "updated_at = now() where user_id = $1",
                user_id, new_chips, new_cash, reputation, now,
                streak_kind, streak_until, celeb_until, celeb_name,
            )

            # Re-fetch units after tick so chips_in_tray is current
            unit_rows = await conn.fetch(
                "select u.*, c.kind, c.tier, c.base_chips_per_sec, c.capacity, c.icon, c.name as unit_name "
                "from tycoon_units u join tycoon_units_catalog c on c.key = u.unit_key "
                "where u.user_id = $1 order by u.placed_at",
                user_id,
            )

    # Build response
    units = []
    for u in unit_rows:
        units.append({
            "id":            int(u["id"]),
            "key":           u["unit_key"],
            "name":          u["unit_name"],
            "kind":          u["kind"],
            "tier":          int(u["tier"]),
            "icon":          u["icon"],
            "level":         int(u["level"]),
            "cell_x":        int(u["cell_x"]),
            "cell_y":        int(u["cell_y"]),
            "capacity":      int(u["capacity"]),
            "chips_in_tray": int(u["chips_in_tray"]),
            "occupancy_pct": float(u.get("occupancy_pct") or 0),
            "chips_per_sec": round(chips_per_sec_per_unit.get(int(u["id"]), 0.0), 2),
        })
    catalog = await _list_catalog(reputation, _list_unit_keys_owned(unit_rows))
    bots_payload = [{"id": int(r["id"]), "kind": r["kind"], "level": int(r["level"])} for r in bot_rows]
    decor_payload = []
    for d in decor_rows:
        if d.get("inv_exists") is None:
            continue
        decor_payload.append({
            "id":        int(d["id"]),
            "inv_id":    int(d["inv_id"]),
            "slot":      int(d["slot_index"]),
            "name":      d["full_name"],
            "image_url": d["image_url"],
            "rarity":    d.get("cat_rarity") or d.get("rarity"),
            "rep_bonus": DECOR_REP_PER_RARITY.get(d.get("cat_rarity") or "", 0.0),
        })

    cap_left = max(0, COINS_DAILY_CAP_BASE - int(state.get("bank_conv_today") or 0)
                   if state.get("last_bank_conv_day") == datetime.now(timezone.utc).date() else COINS_DAILY_CAP_BASE)

    # Themes — owned + catalog
    raw_owned = state.get("themes_owned")
    if raw_owned is None:
        themes_owned = ["vegas"]
    elif isinstance(raw_owned, list):
        themes_owned = raw_owned
    else:
        try:
            themes_owned = json.loads(raw_owned)
        except Exception:
            themes_owned = ["vegas"]
    themes_payload = []
    for tk, tcfg in THEMES.items():
        themes_payload.append({**tcfg, "owned": tk in themes_owned, "selected": tk == state.get("theme")})

    # News feed
    news_raw = state.get("news") or []
    news_items = news_raw if isinstance(news_raw, list) else json.loads(news_raw or "[]")

    # Daily missions
    daily_missions = await _get_or_create_daily_missions(user_id)

    return {
        "ok":             True,
        "chips":          int(new_chips),
        "cash":           int(new_cash),
        "vip_stars":      int(state["vip_stars"]),
        "reputation":     round(reputation, 2),
        "floor_capacity": int(state["floor_capacity"]),
        "theme":          state["theme"],
        "prestige_count": int(state["prestige_count"]),
        "lifetime_cash":  int(state["total_lifetime_cash"]),
        "next_cell_cost": _next_cell_cost(int(state["floor_capacity"])),
        "max_floor":      MAX_FLOOR_CAPACITY,
        "bank_cap_left":  int(cap_left),
        "bank_cap_total": COINS_DAILY_CAP_BASE,
        "chips_to_cash_rate": CHIPS_TO_CASH_RATE,
        "cash_to_coins_rate": CASH_TO_COINS_RATE,
        "units":          units,
        "bots":           bots_payload,
        "decor":          decor_payload,
        "catalog":        catalog,
        "bot_kinds":      [
            {"key": k, **v, "owned": _bot_counts(bot_rows).get(k, 0)} for k, v in BOT_KINDS.items()
        ],
        "themes":         themes_payload,
        "streak": {
            "kind":          streak_kind,
            "seconds_left":  int((streak_until - datetime.now(timezone.utc)).total_seconds()) if streak_until else 0,
            "income_mult":   streak_mult,
        },
        "celeb": {
            "active":        bool(celeb_until and celeb_until > datetime.now(timezone.utc)),
            "name":          celeb_name if celeb_until and celeb_until > datetime.now(timezone.utc) else None,
            "seconds_left":  int((celeb_until - datetime.now(timezone.utc)).total_seconds()) if (celeb_until and celeb_until > datetime.now(timezone.utc)) else 0,
            "income_mult":   celeb_mult,
        },
        "global_income_mult": round(global_income_mult, 3),
        "news":           news_items,
        "missions":       daily_missions,
    }


def _list_unit_keys_owned(rows) -> set[str]:
    return {r["unit_key"] for r in rows}


async def _list_catalog(reputation: float, owned: set[str]) -> list[dict]:
    async with pool().acquire() as conn:
        rows = await conn.fetch("select * from tycoon_units_catalog order by tier, cost_cash")
    out = []
    for r in rows:
        out.append({
            "key":              r["key"],
            "name":             r["name"],
            "kind":             r["kind"],
            "tier":             int(r["tier"]),
            "cost_cash":        int(r["cost_cash"]),
            "cost_chips":       int(r["cost_chips"]),
            "base_chips_per_sec": float(r["base_chips_per_sec"]),
            "capacity":         int(r["capacity"]),
            "unlock_reputation": float(r["unlock_reputation"]),
            "icon":             r["icon"],
            "description":      r["description"],
            "unlocked":         reputation >= float(r["unlock_reputation"]),
        })
    return out


def _next_cell_cost(current_capacity: int) -> int:
    if current_capacity >= MAX_FLOOR_CAPACITY:
        return 0
    growth = current_capacity - START_FLOOR_CAPACITY
    return int(CELL_BUY_BASE_COST * (CELL_BUY_GROWTH ** growth))


# ============================================================
# ACTIONS
# ============================================================

async def buy_unit(user_id: int, unit_key: str, cell_x: int, cell_y: int) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            await _ensure_state(conn, user_id)
            cat = await conn.fetchrow("select * from tycoon_units_catalog where key = $1", unit_key)
            if cat is None:
                return {"ok": False, "error": "Unknown unit"}
            state = await conn.fetchrow("select * from tycoon_state where user_id = $1 for update", user_id)
            cap = int(state["floor_capacity"])
            # Validate cell
            grid_w = 3 if cap <= 6 else 4 if cap <= 12 else 5 if cap <= 20 else 6
            if cell_x < 0 or cell_y < 0 or cell_x >= grid_w:
                return {"ok": False, "error": "Cell out of bounds"}
            placed_count = await conn.fetchval(
                "select count(*) from tycoon_units where user_id = $1", user_id,
            )
            if int(placed_count or 0) >= cap:
                return {"ok": False, "error": f"Зал переполнен ({cap}/{cap}). Расширь этаж."}
            # Cell already taken?
            occupied = await conn.fetchval(
                "select 1 from tycoon_units where user_id = $1 and cell_x = $2 and cell_y = $3",
                user_id, cell_x, cell_y,
            )
            if occupied:
                return {"ok": False, "error": "Эта ячейка занята"}
            # Reputation gate
            rep = float(state["reputation_stars"])
            if rep < float(cat["unlock_reputation"]):
                return {"ok": False, "error": f"Нужно ⭐{cat['unlock_reputation']:.1f} (сейчас {rep:.1f})"}
            # Cost
            cost_cash  = int(cat["cost_cash"])
            cost_chips = int(cat["cost_chips"])
            if int(state["cash"]) < cost_cash or int(state["chips"]) < cost_chips:
                return {"ok": False, "error": "Не хватает $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2, chips = chips - $3, "
                "total_lifetime_cash = total_lifetime_cash + $2 where user_id = $1",
                user_id, cost_cash, cost_chips,
            )
            await conn.execute(
                "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, $3, $4)",
                user_id, unit_key, cell_x, cell_y,
            )
    try:
        await _bump_mission(user_id, "units_bought", 1)
    except Exception:
        pass
    return await get_state(user_id)


async def collect_unit(user_id: int, unit_id: int) -> dict:
    """Tap a unit's tray to collect chips into wallet."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select chips_in_tray from tycoon_units where id = $1 and user_id = $2 for update",
                unit_id, user_id,
            )
            if row is None:
                return {"ok": False, "error": "Юнит не найден"}
            tray = int(row["chips_in_tray"])
            if tray <= 0:
                return {"ok": True, "collected": 0}
            await conn.execute(
                "update tycoon_units set chips_in_tray = 0, last_collected_at = now() where id = $1", unit_id,
            )
            await conn.execute(
                "update tycoon_state set chips = chips + $2 where user_id = $1",
                user_id, tray,
            )
    try:
        await _bump_mission(user_id, "trays_collected", 1)
        await _bump_mission(user_id, "chips_earned",   tray)
    except Exception:
        pass
    return {"ok": True, "collected": tray}


async def collect_all(user_id: int) -> dict:
    """Sweep all unit trays into wallet in one go."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select coalesce(sum(chips_in_tray), 0) as total from tycoon_units where user_id = $1", user_id,
            )
            total = int(row["total"]) if row else 0
            if total <= 0:
                return {"ok": True, "collected": 0}
            await conn.execute(
                "update tycoon_units set chips_in_tray = 0, last_collected_at = now() where user_id = $1", user_id,
            )
            await conn.execute(
                "update tycoon_state set chips = chips + $2 where user_id = $1", user_id, total,
            )
    return {"ok": True, "collected": total}


async def convert_chips_to_cash(user_id: int, amount_chips: int) -> dict:
    """Player-initiated conversion at the cashier."""
    if amount_chips <= 0:
        return {"ok": False, "error": "Положительное число"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow("select chips, cash from tycoon_state where user_id = $1 for update", user_id)
            if state is None or int(state["chips"]) < amount_chips:
                return {"ok": False, "error": "Не хватает чипов"}
            cash_gain = amount_chips // CHIPS_TO_CASH_RATE
            if cash_gain <= 0:
                return {"ok": False, "error": f"Минимум {CHIPS_TO_CASH_RATE} чипов"}
            spent = cash_gain * CHIPS_TO_CASH_RATE
            await conn.execute(
                "update tycoon_state set chips = chips - $2, cash = cash + $3 where user_id = $1",
                user_id, spent, cash_gain,
            )
    try:
        await _bump_mission(user_id, "cash_converted", cash_gain)
    except Exception:
        pass
    return {"ok": True, "spent_chips": spent, "cash_gained": cash_gain}


async def convert_cash_to_coins(user_id: int, amount_cash: int) -> dict:
    """Player-initiated conversion at the bank — feeds into main app coins (capped/day)."""
    if amount_cash <= 0:
        return {"ok": False, "error": "Положительное число"}
    today = datetime.now(timezone.utc).date()
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select cash, last_bank_conv_day, bank_conv_today, prestige_count "
                "from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None or int(state["cash"]) < amount_cash:
                return {"ok": False, "error": "Не хватает $"}
            # Reset daily counter if new day
            if state["last_bank_conv_day"] != today:
                conv_today = 0
            else:
                conv_today = int(state["bank_conv_today"] or 0)
            # Prestige bonus: cap grows by 50% per prestige
            cap = int(COINS_DAILY_CAP_BASE * (1 + 0.5 * int(state["prestige_count"] or 0)))
            cap_left = max(0, cap - conv_today)
            if cap_left == 0:
                return {"ok": False, "error": f"Дневной лимит конверсии исчерпан ({cap} 🪙)"}
            coins_gain = min(cap_left, amount_cash // CASH_TO_COINS_RATE)
            if coins_gain <= 0:
                return {"ok": False, "error": f"Минимум {CASH_TO_COINS_RATE} $"}
            spent = coins_gain * CASH_TO_COINS_RATE
            await conn.execute(
                "update tycoon_state set cash = cash - $2, "
                "bank_conv_today = $3, last_bank_conv_day = $4 where user_id = $1",
                user_id, spent, conv_today + coins_gain, today,
            )
            # Credit main app coins
            new_bal_row = await conn.fetchrow(
                "update economy_users set balance = balance + $2, total_earned = total_earned + $2 "
                "where tg_id = $1 returning balance",
                user_id, coins_gain,
            )
            new_bal = int(new_bal_row["balance"]) if new_bal_row else None
            await conn.execute(
                "insert into economy_transactions (user_id, amount, kind, reason, balance_after) "
                "values ($1, $2, 'tycoon', $3, $4)",
                user_id, coins_gain, f"tycoon_bank_conv_{spent}_cash", new_bal,
            )
    try:
        await _bump_mission(user_id, "coins_converted", coins_gain)
    except Exception:
        pass
    return {"ok": True, "spent_cash": spent, "coins_gained": coins_gain, "new_balance": new_bal}


async def hire_bot(user_id: int, kind: str) -> dict:
    cfg = BOT_KINDS.get(kind)
    if cfg is None:
        return {"ok": False, "error": "Unknown bot"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow("select cash from tycoon_state where user_id = $1 for update", user_id)
            if state is None:
                return {"ok": False, "error": "No state"}
            count = await conn.fetchval(
                "select count(*) from tycoon_bots where user_id = $1 and kind = $2", user_id, kind,
            )
            if int(count or 0) >= int(cfg["max_count"]):
                return {"ok": False, "error": f"Максимум {cfg['max_count']}"}
            cost = int(cfg["hire_cost"])
            if int(state["cash"]) < cost:
                return {"ok": False, "error": "Не хватает $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2 where user_id = $1", user_id, cost,
            )
            await conn.execute(
                "insert into tycoon_bots (user_id, kind) values ($1, $2)", user_id, kind,
            )
    try:
        await _bump_mission(user_id, "bots_hired", 1)
    except Exception:
        pass
    return await get_state(user_id)


async def fire_bot(user_id: int, bot_id: int) -> dict:
    async with pool().acquire() as conn:
        await conn.execute(
            "delete from tycoon_bots where id = $1 and user_id = $2", bot_id, user_id,
        )
    return {"ok": True}


async def buy_cell(user_id: int) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select cash, floor_capacity from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None:
                return {"ok": False, "error": "No state"}
            cap = int(state["floor_capacity"])
            if cap >= MAX_FLOOR_CAPACITY:
                return {"ok": False, "error": "Этаж максимальный"}
            cost = _next_cell_cost(cap)
            if int(state["cash"]) < cost:
                return {"ok": False, "error": f"Нужно {cost} $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2, floor_capacity = floor_capacity + 1 "
                "where user_id = $1",
                user_id, cost,
            )
    return await get_state(user_id)


async def place_decor(user_id: int, inv_id: int, slot_index: int = 0) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select id, locked, coinflip_lobby_id from economy_inventory "
                "where id = $1 and user_id = $2 for update",
                inv_id, user_id,
            )
            if row is None:
                return {"ok": False, "error": "Скин не твой"}
            if row["locked"] or row["coinflip_lobby_id"]:
                return {"ok": False, "error": "Скин заблокирован (маркет/coinflip)"}
            await conn.execute(
                "insert into tycoon_decor (user_id, inv_id, slot_index) values ($1, $2, $3) "
                "on conflict do nothing",
                user_id, inv_id, slot_index,
            )
    return await get_state(user_id)


async def remove_decor(user_id: int, decor_id: int) -> dict:
    async with pool().acquire() as conn:
        await conn.execute(
            "delete from tycoon_decor where id = $1 and user_id = $2", decor_id, user_id,
        )
    return await get_state(user_id)


async def buy_theme(user_id: int, theme_key: str) -> dict:
    cfg = THEMES.get(theme_key)
    if cfg is None:
        return {"ok": False, "error": "Unknown theme"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select cash, themes_owned from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None:
                return {"ok": False, "error": "No state"}
            owned_raw = state["themes_owned"]
            owned = owned_raw if isinstance(owned_raw, list) else json.loads(owned_raw or "[]")
            if theme_key in owned:
                return {"ok": False, "error": "Уже куплено"}
            cost = int(cfg["cost"])
            if int(state["cash"]) < cost:
                return {"ok": False, "error": f"Нужно {cost:,} $"}
            owned.append(theme_key)
            await conn.execute(
                "update tycoon_state set cash = cash - $2, themes_owned = $3::jsonb where user_id = $1",
                user_id, cost, json.dumps(owned),
            )
    return await get_state(user_id)


async def select_theme(user_id: int, theme_key: str) -> dict:
    cfg = THEMES.get(theme_key)
    if cfg is None:
        return {"ok": False, "error": "Unknown theme"}
    async with pool().acquire() as conn:
        state = await conn.fetchrow(
            "select themes_owned from tycoon_state where user_id = $1", user_id,
        )
        if state is None:
            return {"ok": False, "error": "No state"}
        owned_raw = state["themes_owned"]
        owned = owned_raw if isinstance(owned_raw, list) else json.loads(owned_raw or "[]")
        if theme_key not in owned and theme_key != "vegas":
            return {"ok": False, "error": "Тема не куплена"}
        await conn.execute(
            "update tycoon_state set theme = $2 where user_id = $1", user_id, theme_key,
        )
    return await get_state(user_id)


# ============================================================
# DAILY MISSIONS
# ============================================================

async def _get_or_create_daily_missions(user_id: int) -> list[dict]:
    today = datetime.now(timezone.utc).date()
    async with pool().acquire() as conn:
        row = await conn.fetchrow(
            "select missions from tycoon_daily_missions where user_id = $1 and day = $2",
            user_id, today,
        )
        if row is not None:
            raw = row["missions"]
            return raw if isinstance(raw, list) else json.loads(raw)
        # Roll 3 random missions
        templates = random.sample(TYCOON_DAILY_TEMPLATES, k=3)
        missions = [{**t, "progress": 0, "claimed": False} for t in templates]
        await conn.execute(
            "insert into tycoon_daily_missions (user_id, day, missions) values ($1, $2, $3::jsonb)",
            user_id, today, json.dumps(missions),
        )
    return missions


async def _bump_mission(user_id: int, metric: str, amount: int = 1) -> None:
    """Increment progress on any mission matching the metric for today."""
    today = datetime.now(timezone.utc).date()
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select missions from tycoon_daily_missions where user_id = $1 and day = $2 for update",
                user_id, today,
            )
            if row is None:
                return
            raw = row["missions"]
            missions = raw if isinstance(raw, list) else json.loads(raw)
            changed = False
            for m in missions:
                if m.get("metric") == metric and not m.get("claimed"):
                    if m["progress"] < m["target"]:
                        m["progress"] = min(m["target"], m["progress"] + amount)
                        changed = True
            if changed:
                await conn.execute(
                    "update tycoon_daily_missions set missions = $3::jsonb where user_id = $1 and day = $2",
                    user_id, today, json.dumps(missions),
                )


async def claim_mission(user_id: int, mission_key: str) -> dict:
    today = datetime.now(timezone.utc).date()
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select missions from tycoon_daily_missions where user_id = $1 and day = $2 for update",
                user_id, today,
            )
            if row is None:
                return {"ok": False, "error": "Нет миссий"}
            raw = row["missions"]
            missions = raw if isinstance(raw, list) else json.loads(raw)
            target = next((m for m in missions if m["key"] == mission_key), None)
            if target is None:
                return {"ok": False, "error": "Не найдено"}
            if target.get("claimed"):
                return {"ok": False, "error": "Уже забрано"}
            if target["progress"] < target["target"]:
                return {"ok": False, "error": "Ещё не выполнено"}
            target["claimed"] = True
            await conn.execute(
                "update tycoon_daily_missions set missions = $3::jsonb where user_id = $1 and day = $2",
                user_id, today, json.dumps(missions),
            )
            await conn.execute(
                "update tycoon_state set chips = chips + $2 where user_id = $1",
                user_id, int(target["reward_chips"]),
            )
    return {"ok": True, "reward_chips": int(target["reward_chips"]), "key": mission_key}


# ============================================================
# RAIDS — simple PvP: hit a friend's casino, steal % of cash
# ============================================================

async def list_raid_targets(user_id: int) -> list[dict]:
    """List other players (humans, non-bot) with active casinos sorted by cash."""
    async with pool().acquire() as conn:
        rows = await conn.fetch(
            """
            select t.user_id, t.cash, t.reputation_stars, t.last_raided_at,
                   u.username, u.first_name,
                   (select count(*) from tycoon_bots b where b.user_id = t.user_id and b.kind = 'guard') as guards
            from tycoon_state t
            join users u on u.tg_id = t.user_id
            where t.user_id != $1 and t.user_id != 1
            order by t.cash desc
            limit 30
            """,
            user_id,
        )
    out = []
    now = datetime.now(timezone.utc)
    for r in rows:
        recent = r.get("last_raided_at")
        recently_raided = bool(recent and (now - recent).total_seconds() < RAID_COOLDOWN_HOURS * 3600)
        out.append({
            "user_id":    int(r["user_id"]),
            "name":       r["username"] or r["first_name"] or f"user{r['user_id']}",
            "cash":       int(r["cash"]),
            "reputation": float(r["reputation_stars"]),
            "guards":     int(r["guards"] or 0),
            "recently_raided": recently_raided,
        })
    return out


async def raid(user_id: int, target_id: int) -> dict:
    if user_id == target_id:
        return {"ok": False, "error": "Сам себя?"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            attacker = await conn.fetchrow(
                "select last_raid_at from tycoon_state where user_id = $1 for update", user_id,
            )
            if attacker is None:
                return {"ok": False, "error": "Нет казино"}
            now = datetime.now(timezone.utc)
            if attacker["last_raid_at"] and (now - attacker["last_raid_at"]).total_seconds() < RAID_COOLDOWN_HOURS * 3600:
                left = int(RAID_COOLDOWN_HOURS * 3600 - (now - attacker["last_raid_at"]).total_seconds())
                return {"ok": False, "error": f"КД {left//60} мин"}
            victim = await conn.fetchrow(
                "select cash, last_raided_at from tycoon_state where user_id = $1 for update", target_id,
            )
            if victim is None:
                return {"ok": False, "error": "Цель не найдена"}
            if victim["last_raided_at"] and (now - victim["last_raided_at"]).total_seconds() < RAID_COOLDOWN_HOURS * 3600:
                return {"ok": False, "error": "Цель недавно ограбили — попробуй позже"}
            n_guards = int(await conn.fetchval(
                "select count(*) from tycoon_bots where user_id = $1 and kind = 'guard'", target_id,
            ) or 0)
            success_chance = max(0.05, RAID_SUCCESS_BASE + RAID_BONUS_PER_GUARD * n_guards)
            success = random.random() < success_chance
            steal = 0
            if success:
                steal = int(int(victim["cash"]) * RAID_STEAL_PCT)
                if steal > 0:
                    await conn.execute(
                        "update tycoon_state set cash = cash - $2 where user_id = $1", target_id, steal,
                    )
                    await conn.execute(
                        "update tycoon_state set cash = cash + $2 where user_id = $1", user_id, steal,
                    )
            await conn.execute(
                "update tycoon_state set last_raid_at = $2 where user_id = $1", user_id, now,
            )
            await conn.execute(
                "update tycoon_state set last_raided_at = $2 where user_id = $1", target_id, now,
            )
            # Push news to both sides
            attacker_name = await conn.fetchval(
                "select coalesce(first_name, username, 'кто-то') from users where tg_id = $1", user_id,
            )
            victim_name = await conn.fetchval(
                "select coalesce(first_name, username, 'кто-то') from users where tg_id = $1", target_id,
            )
            if success:
                await _push_news(conn, user_id,
                    f"⚔️ Ограбил {victim_name}! Унёс {steal:,} $.")
                await _push_news(conn, target_id,
                    f"💀 {attacker_name} налетел и стащил {steal:,} $!")
            else:
                await _push_news(conn, user_id,
                    f"🛡 Налёт на {victim_name} провалился — охрана отбила.")
                await _push_news(conn, target_id,
                    f"🛡 Охрана отбила налёт от {attacker_name}.")
    return {
        "ok": True,
        "success": success,
        "stolen": steal,
        "guards_at_target": n_guards,
        "success_chance": round(success_chance, 2),
    }


# ============================================================
# Original prestige (extended with celeb/streak reset)
# ============================================================

async def prestige(user_id: int) -> dict:
    """Reset everything for VIP stars. Threshold = $1B lifetime cash."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select * from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None or int(state["total_lifetime_cash"]) < PRESTIGE_THRESHOLD:
                return {"ok": False, "error": f"Нужно {PRESTIGE_THRESHOLD/1e9:.1f}B $ суммарно"}
            new_stars = int(math.log10(max(1, int(state["total_lifetime_cash"]) / PRESTIGE_THRESHOLD))) + 1
            await conn.execute(
                "update tycoon_state set "
                "  chips = 0, cash = 1000, "
                "  reputation_stars = 1.0, floor_capacity = $2, "
                "  vip_stars = vip_stars + $3, "
                "  prestige_count = prestige_count + 1, "
                "  total_lifetime_cash = 0, "
                "  bank_conv_today = 0, last_bank_conv_day = null, "
                "  last_tick_at = now(), updated_at = now() "
                "where user_id = $1",
                user_id, START_FLOOR_CAPACITY, new_stars,
            )
            await conn.execute("delete from tycoon_units where user_id = $1", user_id)
            await conn.execute("delete from tycoon_bots where user_id = $1", user_id)
            # Decor stays — they're player's skins
            # Re-insert starter slot
            await conn.execute(
                "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, 1, 0)",
                user_id, "slot_basic",
            )
    return await get_state(user_id)
