"""Casino Tycoon — build-your-own-casino idle/active hybrid.

Three-currency model:
  chips  ($T) — internal grind currency, generated by units when occupied
  cash   ($)  — mid-tier, converted from chips at the cashier (player UX)
  coins  (🪙) — main app currency, converted from cash at the bank (capped/day)
  vip    ⭐   — prestige tokens, gained only via full reset

Game tick: server runs a periodic 'tick' on every state-fetch call (idempotent,
based on last_tick_at delta). During the tick:
  • each unit accrues chips into its tray, scaled by occupancy and bot bonuses
  • cashier bot auto-converts a fraction of chips to cash
  • slot-attendant bot auto-collects trays into chips
  • staff salaries are deducted

Visitor spawning is purely visual on the frontend — server doesn't simulate
individual visitors. Instead it computes an aggregate occupancy_pct per unit
based on the current reputation + unit tier + bot bonuses, and the frontend
samples that to drive the visual show.
"""
from __future__ import annotations

import json
import logging
import math
import random
from datetime import datetime, timezone
from pathlib import Path

from app.db.client import pool

log = logging.getLogger(__name__)


# ============================================================
# CONFIG / CATALOG (will be seeded into tycoon_units_catalog)
# ============================================================

# (key, name, kind, tier, cost_cash, cost_chips, base_chips_per_sec, capacity, unlock_rep, icon, desc)
UNIT_CATALOG: list[dict] = [
    # ----- SLOTS (stack vertically across tiers) -----
    {"key": "slot_basic",    "name": "Slot Basic",    "kind": "slot", "tier": 1,
     "cost_cash": 500,    "cost_chips": 0,     "base_chips_per_sec": 5,    "capacity": 1, "unlock_rep": 0,
     "icon": "🎰", "description": "Старушка-однорукий, копейки но капают всегда"},
    {"key": "slot_lucky7",   "name": "Lucky 7",       "kind": "slot", "tier": 2,
     "cost_cash": 2_500,  "cost_chips": 0,     "base_chips_per_sec": 18,   "capacity": 1, "unlock_rep": 1.0,
     "icon": "7️⃣", "description": "Красные семёрки, любимая бабушек на пенсии"},
    {"key": "slot_pirate",   "name": "Pirate Booty",  "kind": "slot", "tier": 3,
     "cost_cash": 8_000,  "cost_chips": 0,     "base_chips_per_sec": 50,   "capacity": 1, "unlock_rep": 1.5,
     "icon": "🏴‍☠️", "description": "Сундук, попугай, x100 на трёх якорях"},
    {"key": "slot_royale",   "name": "Royal Flush",   "kind": "slot", "tier": 4,
     "cost_cash": 25_000, "cost_chips": 0,     "base_chips_per_sec": 150,  "capacity": 1, "unlock_rep": 2.5,
     "icon": "👑", "description": "Премиум для среднего класса"},
    {"key": "slot_csgates",  "name": "CS Gates",      "kind": "slot", "tier": 5,
     "cost_cash": 80_000, "cost_chips": 0,     "base_chips_per_sec": 400,  "capacity": 1, "unlock_rep": 3.5,
     "icon": "💣", "description": "Тематический под наш main-game CS Gates"},

    # ----- TABLES (multi-seat) -----
    {"key": "tbl_coinflip",  "name": "Стол Coinflip", "kind": "table", "tier": 2,
     "cost_cash": 5_000,  "cost_chips": 0,     "base_chips_per_sec": 25,   "capacity": 2, "unlock_rep": 1.0,
     "icon": "🪙", "description": "Простейшая дуэль 1v1"},
    {"key": "tbl_roulette",  "name": "Рулетка",       "kind": "table", "tier": 3,
     "cost_cash": 30_000, "cost_chips": 0,     "base_chips_per_sec": 200,  "capacity": 6, "unlock_rep": 2.0,
     "icon": "🎡", "description": "Классика, 6 мест, красное-чёрное-зелёное"},
    {"key": "tbl_blackjack", "name": "Блэкджек",      "kind": "table", "tier": 4,
     "cost_cash": 50_000, "cost_chips": 0,     "base_chips_per_sec": 320,  "capacity": 4, "unlock_rep": 2.5,
     "icon": "🃏", "description": "21, дилер раздаёт без устали"},
    {"key": "tbl_poker_vip", "name": "Покер VIP",     "kind": "table", "tier": 5,
     "cost_cash": 200_000,"cost_chips": 0,     "base_chips_per_sec": 1500, "capacity": 6, "unlock_rep": 3.5,
     "icon": "♠", "description": "Высокие ставки, заходят только хайроллеры"},

    # ----- AMENITIES (don't generate chips directly, boost others) -----
    {"key": "amen_bar",      "name": "Бар",           "kind": "amenity", "tier": 2,
     "cost_cash": 15_000, "cost_chips": 0,     "base_chips_per_sec": 0,    "capacity": 4, "unlock_rep": 1.5,
     "icon": "🍸", "description": "+20% к среднему кошельку гостя (через repu)"},
    {"key": "amen_atm",      "name": "Банкомат",      "kind": "amenity", "tier": 2,
     "cost_cash": 25_000, "cost_chips": 0,     "base_chips_per_sec": 0,    "capacity": 1, "unlock_rep": 2.0,
     "icon": "🏧", "description": "Гости тратят больше; +reputation"},
    {"key": "amen_vip",      "name": "VIP-зона",      "kind": "amenity", "tier": 5,
     "cost_cash": 1_000_000, "cost_chips": 0,  "base_chips_per_sec": 0,    "capacity": 1, "unlock_rep": 4.0,
     "icon": "🌟", "description": "Открывает приток китов; огромный реп-бонус"},
]


# ============================================================
# BOT TYPES (effects applied at tick)
# ============================================================

BOT_KINDS: dict[str, dict] = {
    "slot_attendant": {
        "name":          "Слот-аттендант",
        "icon":          "🧑‍🔧",
        "hire_cost":     5_000,    # cash
        "salary_per_hr": 300,      # chips/hour
        "max_count":     5,
        "description":   "Авто-собирает подносы со слотов (1 бот = 5 слотов)",
    },
    "cashier": {
        "name":          "Кассир",
        "icon":          "💼",
        "hire_cost":     10_000,
        "salary_per_hr": 200,
        "max_count":     1,
        "description":   "Авто-конверсия 50% накопленных чипов в $ при тике",
    },
    "dealer": {
        "name":          "Дилер",
        "icon":          "🃏",
        "hire_cost":     30_000,
        "salary_per_hr": 500,
        "max_count":     5,
        "description":   "+50% к скорости столов",
    },
    "manager": {
        "name":          "Менеджер",
        "icon":          "🎩",
        "hire_cost":     200_000,
        "salary_per_hr": 2_000,
        "max_count":     1,
        "description":   "+15% к доходу всего казино",
    },
    "cleaner": {
        "name":          "Уборщик",
        "icon":          "🧹",
        "hire_cost":     2_000,
        "salary_per_hr": 50,
        "max_count":     3,
        "description":   "+0.5⭐ к репутации (за бота, до +1.5)",
    },
}


# ============================================================
# ECONOMY CONSTANTS
# ============================================================

CHIPS_TO_CASH_RATE   = 100              # 100 chips → 1 $ (player click conversion)
CASH_TO_COINS_RATE   = 1_000            # 1000 $ → 1 coin (bank conversion)
COINS_DAILY_CAP_BASE = 5_000            # base daily coin-conversion cap
PRESTIGE_THRESHOLD   = 1_000_000_000    # $1B lifetime cash to unlock prestige

START_FLOOR_CAPACITY = 6                # 3x2 grid at start
MAX_FLOOR_CAPACITY   = 24               # 6x4 endgame
CELL_BUY_BASE_COST   = 5_000            # cost to unlock cell N+1
CELL_BUY_GROWTH      = 1.6              # multiplied per cell

DECOR_REP_PER_RARITY = {                # reputation bonus per displayed skin
    "consumer": 0.0, "industrial": 0.0, "mil-spec": 0.05,
    "restricted": 0.1, "classified": 0.2,
    "covert": 0.4, "exceedingly_rare": 0.8,
}


# ============================================================
# SCHEMA + SEED
# ============================================================

async def ensure_schema() -> None:
    sql_path = Path(__file__).parent.parent / "db" / "migration_tycoon.sql"
    if not sql_path.exists():
        log.warning("tycoon migration SQL missing")
        return
    sql = sql_path.read_text(encoding="utf-8")
    async with pool().acquire() as conn:
        await conn.execute(sql)
        # Seed catalog rows (idempotent: ON CONFLICT updates)
        for u in UNIT_CATALOG:
            await conn.execute(
                """
                insert into tycoon_units_catalog
                  (key, name, kind, tier, cost_cash, cost_chips, base_chips_per_sec,
                   capacity, unlock_reputation, icon, description)
                values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
                on conflict (key) do update set
                  name = excluded.name, kind = excluded.kind, tier = excluded.tier,
                  cost_cash = excluded.cost_cash, cost_chips = excluded.cost_chips,
                  base_chips_per_sec = excluded.base_chips_per_sec,
                  capacity = excluded.capacity,
                  unlock_reputation = excluded.unlock_reputation,
                  icon = excluded.icon, description = excluded.description
                """,
                u["key"], u["name"], u["kind"], u["tier"],
                u["cost_cash"], u["cost_chips"], u["base_chips_per_sec"],
                u["capacity"], u["unlock_rep"], u["icon"], u["description"],
            )
    log.info("tycoon schema + catalog seeded (%d units)", len(UNIT_CATALOG))


# ============================================================
# CORE — get state (also runs the offline tick)
# ============================================================

async def _ensure_state(conn, user_id: int) -> None:
    """Create initial state row + 1 starter slot if user is brand new."""
    row = await conn.fetchrow("select user_id from tycoon_state where user_id = $1", user_id)
    if row is not None:
        return
    await conn.execute(
        "insert into tycoon_state (user_id, chips, cash, floor_capacity, reputation_stars) "
        "values ($1, 0, 1000, $2, 1.0)",
        user_id, START_FLOOR_CAPACITY,
    )
    # Starter slot at cell (1,0) — center of top row
    await conn.execute(
        "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, 1, 0)",
        user_id, "slot_basic",
    )


def _bot_counts(rows: list) -> dict[str, int]:
    out: dict[str, int] = {}
    for r in rows:
        out[r["kind"]] = out.get(r["kind"], 0) + 1
    return out


def _compute_occupancy(reputation: float, unit_tier: int, manager_bonus: float) -> float:
    """0..1 occupancy estimate. Higher rep = more visitors. Higher-tier units
    need more rep to fill up — they only really shine at 4-5 stars."""
    rep_factor    = max(0.0, min(1.0, (reputation - 0.5) / 4.5))
    tier_demand   = 1.0 - 0.10 * (unit_tier - 1)   # tier 5 needs ~1.4× more rep
    base = 0.20 + 0.65 * rep_factor * tier_demand
    return max(0.0, min(0.95, base * manager_bonus))


def _chips_per_sec_for_unit(u: dict, occupancy: float, dealer_factor: float, manager_bonus: float) -> float:
    """Effective chips/sec considering occupancy + dealer (tables) + manager."""
    base = float(u["base_chips_per_sec"]) * (1.0 + 0.5 * (u["level"] - 1))
    dealer_mult = dealer_factor if u["kind"] == "table" else 1.0
    return base * occupancy * dealer_mult * manager_bonus


async def get_state(user_id: int) -> dict:
    """Read state, run offline tick, return full snapshot for the frontend."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            await _ensure_state(conn, user_id)
            state = dict(await conn.fetchrow("select * from tycoon_state where user_id = $1", user_id))
            unit_rows = await conn.fetch(
                "select u.*, c.kind, c.tier, c.base_chips_per_sec, c.capacity, c.icon, c.name as unit_name "
                "from tycoon_units u join tycoon_units_catalog c on c.key = u.unit_key "
                "where u.user_id = $1 order by u.placed_at",
                user_id,
            )
            bot_rows = await conn.fetch(
                "select * from tycoon_bots where user_id = $1", user_id,
            )
            decor_rows = await conn.fetch(
                "select d.id, d.inv_id, d.slot_index, "
                "       i.id as inv_exists, i.skin_id, i.price, i.rarity, "
                "       s.full_name, s.image_url, s.rarity as cat_rarity "
                "from tycoon_decor d "
                "left join economy_inventory i on i.id = d.inv_id "
                "left join economy_skins_catalog s on s.id = i.skin_id "
                "where d.user_id = $1 order by d.slot_index",
                user_id,
            )

            now = datetime.now(timezone.utc)
            elapsed = (now - state["last_tick_at"]).total_seconds()
            elapsed = max(0.0, min(elapsed, 12 * 3600))   # cap offline at 12h

            # Bot effects
            bots = _bot_counts(bot_rows)
            n_attendants    = bots.get("slot_attendant", 0)
            has_cashier     = bots.get("cashier", 0) > 0
            n_dealers       = bots.get("dealer", 0)
            has_manager     = bots.get("manager", 0) > 0
            n_cleaners      = bots.get("cleaner", 0)
            dealer_factor   = 1.0 + 0.5 * min(n_dealers, 5)         # +50% per dealer up to 5
            manager_bonus   = 1.15 if has_manager else 1.0
            cleaner_rep     = min(1.5, 0.5 * n_cleaners)
            decor_rep_bonus = 0.0
            for d in decor_rows:
                rar = d.get("cat_rarity") or d.get("rarity")
                if rar and d.get("inv_exists") is not None:
                    decor_rep_bonus += DECOR_REP_PER_RARITY.get(rar, 0.0)
            decor_rep_bonus = min(2.0, decor_rep_bonus)              # cap so single user can't grind 5⭐ via decor only

            # Reputation = 1 (base) + 0.4 per amenity + cleaner_rep + decor — capped 5
            n_amenities = sum(1 for u in unit_rows if u["kind"] == "amenity")
            reputation = 1.0 + 0.4 * n_amenities + cleaner_rep + decor_rep_bonus
            reputation = max(0.0, min(5.0, reputation))

            # Run tick: each unit accrues chips, attendants auto-collect, cashier auto-converts
            new_chips = int(state["chips"])
            new_cash  = int(state["cash"])
            occupancy_per_unit: dict[int, float] = {}
            chips_per_sec_per_unit: dict[int, float] = {}
            for u in unit_rows:
                occ = _compute_occupancy(reputation, int(u["tier"]), manager_bonus)
                cps = _chips_per_sec_for_unit(dict(u), occ, dealer_factor, manager_bonus)
                occupancy_per_unit[u["id"]]    = occ
                chips_per_sec_per_unit[u["id"]] = cps
                gen = int(cps * elapsed)
                if gen <= 0:
                    continue
                # Attendants auto-collect a fraction of generated chips into the player's wallet.
                # Otherwise chips pile up in the unit's tray for manual collection.
                if u["kind"] in ("slot", "table") and n_attendants > 0:
                    auto_pct = min(1.0, n_attendants * 0.20)         # 1 bot=20%, 5 bots=100%
                    auto_part = int(gen * auto_pct)
                    tray_part = gen - auto_part
                    new_chips += auto_part
                    if tray_part > 0:
                        await conn.execute(
                            "update tycoon_units set chips_in_tray = chips_in_tray + $2, "
                            "occupancy_pct = $3, last_collected_at = greatest(last_collected_at, $4) "
                            "where id = $1",
                            int(u["id"]), tray_part, occ * 100, now,
                        )
                    else:
                        await conn.execute(
                            "update tycoon_units set occupancy_pct = $2 where id = $1",
                            int(u["id"]), occ * 100,
                        )
                else:
                    await conn.execute(
                        "update tycoon_units set chips_in_tray = chips_in_tray + $2, occupancy_pct = $3 "
                        "where id = $1",
                        int(u["id"]), gen, occ * 100,
                    )

            # Cashier auto-converts wallet chips to cash periodically
            if has_cashier and new_chips > 200:
                conv_chips = int(new_chips * 0.50)                   # 50% per tick
                conv_cash  = conv_chips // CHIPS_TO_CASH_RATE
                if conv_cash > 0:
                    new_chips -= conv_chips
                    new_cash  += conv_cash

            # Salaries (per-hour rate × elapsed hours), paid in chips
            salary_chips = 0
            for kind, count in bots.items():
                cfg = BOT_KINDS.get(kind)
                if cfg:
                    salary_chips += int(cfg["salary_per_hr"] * count * (elapsed / 3600.0))
            if salary_chips > 0:
                if new_chips >= salary_chips:
                    new_chips -= salary_chips
                else:
                    # Player went negative — bots quietly stop working (no -chips, but log)
                    salary_chips = new_chips
                    new_chips = 0

            # Persist state changes from tick
            await conn.execute(
                "update tycoon_state set chips = $2, cash = $3, reputation_stars = $4, last_tick_at = $5, "
                "updated_at = now() where user_id = $1",
                user_id, new_chips, new_cash, reputation, now,
            )

            # Re-fetch units after tick so chips_in_tray is current
            unit_rows = await conn.fetch(
                "select u.*, c.kind, c.tier, c.base_chips_per_sec, c.capacity, c.icon, c.name as unit_name "
                "from tycoon_units u join tycoon_units_catalog c on c.key = u.unit_key "
                "where u.user_id = $1 order by u.placed_at",
                user_id,
            )

    # Build response
    units = []
    for u in unit_rows:
        units.append({
            "id":            int(u["id"]),
            "key":           u["unit_key"],
            "name":          u["unit_name"],
            "kind":          u["kind"],
            "tier":          int(u["tier"]),
            "icon":          u["icon"],
            "level":         int(u["level"]),
            "cell_x":        int(u["cell_x"]),
            "cell_y":        int(u["cell_y"]),
            "capacity":      int(u["capacity"]),
            "chips_in_tray": int(u["chips_in_tray"]),
            "occupancy_pct": float(u.get("occupancy_pct") or 0),
            "chips_per_sec": round(chips_per_sec_per_unit.get(int(u["id"]), 0.0), 2),
        })
    catalog = await _list_catalog(reputation, _list_unit_keys_owned(unit_rows))
    bots_payload = [{"id": int(r["id"]), "kind": r["kind"], "level": int(r["level"])} for r in bot_rows]
    decor_payload = []
    for d in decor_rows:
        if d.get("inv_exists") is None:
            continue
        decor_payload.append({
            "id":        int(d["id"]),
            "inv_id":    int(d["inv_id"]),
            "slot":      int(d["slot_index"]),
            "name":      d["full_name"],
            "image_url": d["image_url"],
            "rarity":    d.get("cat_rarity") or d.get("rarity"),
            "rep_bonus": DECOR_REP_PER_RARITY.get(d.get("cat_rarity") or "", 0.0),
        })

    cap_left = max(0, COINS_DAILY_CAP_BASE - int(state.get("bank_conv_today") or 0)
                   if state.get("last_bank_conv_day") == datetime.now(timezone.utc).date() else COINS_DAILY_CAP_BASE)

    return {
        "ok":             True,
        "chips":          int(new_chips),
        "cash":           int(new_cash),
        "vip_stars":      int(state["vip_stars"]),
        "reputation":     round(reputation, 2),
        "floor_capacity": int(state["floor_capacity"]),
        "theme":          state["theme"],
        "prestige_count": int(state["prestige_count"]),
        "lifetime_cash":  int(state["total_lifetime_cash"]),
        "next_cell_cost": _next_cell_cost(int(state["floor_capacity"])),
        "max_floor":      MAX_FLOOR_CAPACITY,
        "bank_cap_left":  int(cap_left),
        "bank_cap_total": COINS_DAILY_CAP_BASE,
        "chips_to_cash_rate": CHIPS_TO_CASH_RATE,
        "cash_to_coins_rate": CASH_TO_COINS_RATE,
        "units":          units,
        "bots":           bots_payload,
        "decor":          decor_payload,
        "catalog":        catalog,
        "bot_kinds":      [
            {"key": k, **v, "owned": _bot_counts(bot_rows).get(k, 0)} for k, v in BOT_KINDS.items()
        ],
    }


def _list_unit_keys_owned(rows) -> set[str]:
    return {r["unit_key"] for r in rows}


async def _list_catalog(reputation: float, owned: set[str]) -> list[dict]:
    async with pool().acquire() as conn:
        rows = await conn.fetch("select * from tycoon_units_catalog order by tier, cost_cash")
    out = []
    for r in rows:
        out.append({
            "key":              r["key"],
            "name":             r["name"],
            "kind":             r["kind"],
            "tier":             int(r["tier"]),
            "cost_cash":        int(r["cost_cash"]),
            "cost_chips":       int(r["cost_chips"]),
            "base_chips_per_sec": float(r["base_chips_per_sec"]),
            "capacity":         int(r["capacity"]),
            "unlock_reputation": float(r["unlock_reputation"]),
            "icon":             r["icon"],
            "description":      r["description"],
            "unlocked":         reputation >= float(r["unlock_reputation"]),
        })
    return out


def _next_cell_cost(current_capacity: int) -> int:
    if current_capacity >= MAX_FLOOR_CAPACITY:
        return 0
    growth = current_capacity - START_FLOOR_CAPACITY
    return int(CELL_BUY_BASE_COST * (CELL_BUY_GROWTH ** growth))


# ============================================================
# ACTIONS
# ============================================================

async def buy_unit(user_id: int, unit_key: str, cell_x: int, cell_y: int) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            await _ensure_state(conn, user_id)
            cat = await conn.fetchrow("select * from tycoon_units_catalog where key = $1", unit_key)
            if cat is None:
                return {"ok": False, "error": "Unknown unit"}
            state = await conn.fetchrow("select * from tycoon_state where user_id = $1 for update", user_id)
            cap = int(state["floor_capacity"])
            # Validate cell
            grid_w = 3 if cap <= 6 else 4 if cap <= 12 else 5 if cap <= 20 else 6
            if cell_x < 0 or cell_y < 0 or cell_x >= grid_w:
                return {"ok": False, "error": "Cell out of bounds"}
            placed_count = await conn.fetchval(
                "select count(*) from tycoon_units where user_id = $1", user_id,
            )
            if int(placed_count or 0) >= cap:
                return {"ok": False, "error": f"Зал переполнен ({cap}/{cap}). Расширь этаж."}
            # Cell already taken?
            occupied = await conn.fetchval(
                "select 1 from tycoon_units where user_id = $1 and cell_x = $2 and cell_y = $3",
                user_id, cell_x, cell_y,
            )
            if occupied:
                return {"ok": False, "error": "Эта ячейка занята"}
            # Reputation gate
            rep = float(state["reputation_stars"])
            if rep < float(cat["unlock_reputation"]):
                return {"ok": False, "error": f"Нужно ⭐{cat['unlock_reputation']:.1f} (сейчас {rep:.1f})"}
            # Cost
            cost_cash  = int(cat["cost_cash"])
            cost_chips = int(cat["cost_chips"])
            if int(state["cash"]) < cost_cash or int(state["chips"]) < cost_chips:
                return {"ok": False, "error": "Не хватает $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2, chips = chips - $3, "
                "total_lifetime_cash = total_lifetime_cash + $2 where user_id = $1",
                user_id, cost_cash, cost_chips,
            )
            await conn.execute(
                "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, $3, $4)",
                user_id, unit_key, cell_x, cell_y,
            )
    return await get_state(user_id)


async def collect_unit(user_id: int, unit_id: int) -> dict:
    """Tap a unit's tray to collect chips into wallet."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select chips_in_tray from tycoon_units where id = $1 and user_id = $2 for update",
                unit_id, user_id,
            )
            if row is None:
                return {"ok": False, "error": "Юнит не найден"}
            tray = int(row["chips_in_tray"])
            if tray <= 0:
                return {"ok": True, "collected": 0}
            await conn.execute(
                "update tycoon_units set chips_in_tray = 0, last_collected_at = now() where id = $1", unit_id,
            )
            await conn.execute(
                "update tycoon_state set chips = chips + $2 where user_id = $1",
                user_id, tray,
            )
    return {"ok": True, "collected": tray}


async def collect_all(user_id: int) -> dict:
    """Sweep all unit trays into wallet in one go."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select coalesce(sum(chips_in_tray), 0) as total from tycoon_units where user_id = $1", user_id,
            )
            total = int(row["total"]) if row else 0
            if total <= 0:
                return {"ok": True, "collected": 0}
            await conn.execute(
                "update tycoon_units set chips_in_tray = 0, last_collected_at = now() where user_id = $1", user_id,
            )
            await conn.execute(
                "update tycoon_state set chips = chips + $2 where user_id = $1", user_id, total,
            )
    return {"ok": True, "collected": total}


async def convert_chips_to_cash(user_id: int, amount_chips: int) -> dict:
    """Player-initiated conversion at the cashier."""
    if amount_chips <= 0:
        return {"ok": False, "error": "Положительное число"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow("select chips, cash from tycoon_state where user_id = $1 for update", user_id)
            if state is None or int(state["chips"]) < amount_chips:
                return {"ok": False, "error": "Не хватает чипов"}
            cash_gain = amount_chips // CHIPS_TO_CASH_RATE
            if cash_gain <= 0:
                return {"ok": False, "error": f"Минимум {CHIPS_TO_CASH_RATE} чипов"}
            spent = cash_gain * CHIPS_TO_CASH_RATE
            await conn.execute(
                "update tycoon_state set chips = chips - $2, cash = cash + $3 where user_id = $1",
                user_id, spent, cash_gain,
            )
    return {"ok": True, "spent_chips": spent, "cash_gained": cash_gain}


async def convert_cash_to_coins(user_id: int, amount_cash: int) -> dict:
    """Player-initiated conversion at the bank — feeds into main app coins (capped/day)."""
    if amount_cash <= 0:
        return {"ok": False, "error": "Положительное число"}
    today = datetime.now(timezone.utc).date()
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select cash, last_bank_conv_day, bank_conv_today, prestige_count "
                "from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None or int(state["cash"]) < amount_cash:
                return {"ok": False, "error": "Не хватает $"}
            # Reset daily counter if new day
            if state["last_bank_conv_day"] != today:
                conv_today = 0
            else:
                conv_today = int(state["bank_conv_today"] or 0)
            # Prestige bonus: cap grows by 50% per prestige
            cap = int(COINS_DAILY_CAP_BASE * (1 + 0.5 * int(state["prestige_count"] or 0)))
            cap_left = max(0, cap - conv_today)
            if cap_left == 0:
                return {"ok": False, "error": f"Дневной лимит конверсии исчерпан ({cap} 🪙)"}
            coins_gain = min(cap_left, amount_cash // CASH_TO_COINS_RATE)
            if coins_gain <= 0:
                return {"ok": False, "error": f"Минимум {CASH_TO_COINS_RATE} $"}
            spent = coins_gain * CASH_TO_COINS_RATE
            await conn.execute(
                "update tycoon_state set cash = cash - $2, "
                "bank_conv_today = $3, last_bank_conv_day = $4 where user_id = $1",
                user_id, spent, conv_today + coins_gain, today,
            )
            # Credit main app coins
            new_bal_row = await conn.fetchrow(
                "update economy_users set balance = balance + $2, total_earned = total_earned + $2 "
                "where tg_id = $1 returning balance",
                user_id, coins_gain,
            )
            new_bal = int(new_bal_row["balance"]) if new_bal_row else None
            await conn.execute(
                "insert into economy_transactions (user_id, amount, kind, reason, balance_after) "
                "values ($1, $2, 'tycoon', $3, $4)",
                user_id, coins_gain, f"tycoon_bank_conv_{spent}_cash", new_bal,
            )
    return {"ok": True, "spent_cash": spent, "coins_gained": coins_gain, "new_balance": new_bal}


async def hire_bot(user_id: int, kind: str) -> dict:
    cfg = BOT_KINDS.get(kind)
    if cfg is None:
        return {"ok": False, "error": "Unknown bot"}
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow("select cash from tycoon_state where user_id = $1 for update", user_id)
            if state is None:
                return {"ok": False, "error": "No state"}
            count = await conn.fetchval(
                "select count(*) from tycoon_bots where user_id = $1 and kind = $2", user_id, kind,
            )
            if int(count or 0) >= int(cfg["max_count"]):
                return {"ok": False, "error": f"Максимум {cfg['max_count']}"}
            cost = int(cfg["hire_cost"])
            if int(state["cash"]) < cost:
                return {"ok": False, "error": "Не хватает $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2 where user_id = $1", user_id, cost,
            )
            await conn.execute(
                "insert into tycoon_bots (user_id, kind) values ($1, $2)", user_id, kind,
            )
    return await get_state(user_id)


async def fire_bot(user_id: int, bot_id: int) -> dict:
    async with pool().acquire() as conn:
        await conn.execute(
            "delete from tycoon_bots where id = $1 and user_id = $2", bot_id, user_id,
        )
    return {"ok": True}


async def buy_cell(user_id: int) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select cash, floor_capacity from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None:
                return {"ok": False, "error": "No state"}
            cap = int(state["floor_capacity"])
            if cap >= MAX_FLOOR_CAPACITY:
                return {"ok": False, "error": "Этаж максимальный"}
            cost = _next_cell_cost(cap)
            if int(state["cash"]) < cost:
                return {"ok": False, "error": f"Нужно {cost} $"}
            await conn.execute(
                "update tycoon_state set cash = cash - $2, floor_capacity = floor_capacity + 1 "
                "where user_id = $1",
                user_id, cost,
            )
    return await get_state(user_id)


async def place_decor(user_id: int, inv_id: int, slot_index: int = 0) -> dict:
    async with pool().acquire() as conn:
        async with conn.transaction():
            row = await conn.fetchrow(
                "select id, locked, coinflip_lobby_id from economy_inventory "
                "where id = $1 and user_id = $2 for update",
                inv_id, user_id,
            )
            if row is None:
                return {"ok": False, "error": "Скин не твой"}
            if row["locked"] or row["coinflip_lobby_id"]:
                return {"ok": False, "error": "Скин заблокирован (маркет/coinflip)"}
            await conn.execute(
                "insert into tycoon_decor (user_id, inv_id, slot_index) values ($1, $2, $3) "
                "on conflict do nothing",
                user_id, inv_id, slot_index,
            )
    return await get_state(user_id)


async def remove_decor(user_id: int, decor_id: int) -> dict:
    async with pool().acquire() as conn:
        await conn.execute(
            "delete from tycoon_decor where id = $1 and user_id = $2", decor_id, user_id,
        )
    return await get_state(user_id)


async def prestige(user_id: int) -> dict:
    """Reset everything for VIP stars. Threshold = $1B lifetime cash."""
    async with pool().acquire() as conn:
        async with conn.transaction():
            state = await conn.fetchrow(
                "select * from tycoon_state where user_id = $1 for update", user_id,
            )
            if state is None or int(state["total_lifetime_cash"]) < PRESTIGE_THRESHOLD:
                return {"ok": False, "error": f"Нужно {PRESTIGE_THRESHOLD/1e9:.1f}B $ суммарно"}
            new_stars = int(math.log10(max(1, int(state["total_lifetime_cash"]) / PRESTIGE_THRESHOLD))) + 1
            await conn.execute(
                "update tycoon_state set "
                "  chips = 0, cash = 1000, "
                "  reputation_stars = 1.0, floor_capacity = $2, "
                "  vip_stars = vip_stars + $3, "
                "  prestige_count = prestige_count + 1, "
                "  total_lifetime_cash = 0, "
                "  bank_conv_today = 0, last_bank_conv_day = null, "
                "  last_tick_at = now(), updated_at = now() "
                "where user_id = $1",
                user_id, START_FLOOR_CAPACITY, new_stars,
            )
            await conn.execute("delete from tycoon_units where user_id = $1", user_id)
            await conn.execute("delete from tycoon_bots where user_id = $1", user_id)
            # Decor stays — they're player's skins
            # Re-insert starter slot
            await conn.execute(
                "insert into tycoon_units (user_id, unit_key, cell_x, cell_y) values ($1, $2, 1, 0)",
                user_id, "slot_basic",
            )
    return await get_state(user_id)
